// 
// This is an autogenerated header file. Do not edit this. If you need
// to change the definitions then change them in RobWorkConfig.hpp.in  
// 

#define RW_VERSION "0.3.1"
#define RW_VERSION_MAJOR 0 
#define RW_VERSION_MINOR 3
#define RW_VERSION_PATCH 1

#define RW_REVISION ""

#define RW_HAVE_PQP 1
#define RW_HAVE_YAOBI 1

